---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zWX1333091.
--- DateTime: 2024/7/3 17:32
---

--require("tests.lua_md5_test")

--[[python:
  	enumerate	function: 000002808D8A2670
  	as_attrgetter	function: 000002808D8A2A00
  	iterex	function: 000002808D8A2640
  	as_itemgetter	function: 000002808D8A2550
  	eval	<built-in function eval>
  	as_function	function: 000002808D8A2610
  	args	function: 000002808D0E15D0
  	builtins	<module 'builtins' (built-in)>
  	set_overflow_handler	function: 000002808D8A2760
  	iter	function: 000002808D8A2280
  	none	None
]]

-- [lupa](https://github.com/scoder/lupa)
-- bad argument #1 to 'enumerate' (not a python object)
--  太妙了，想一想，C 语言的 userdata！！！
--for k, v in python.enumerate(table) do
--    print(k, v)
--end

--fn({
--    [true] = "v_true",
--    [1] = "v_1",
--    [1.1] = "v_1.1",
--    ["k_aaa"] = "v_aaa",
--    [function()
--    end] = "v_function",
--    [coroutine.create(function()
--    end)] = "v_thread",
--    [{}] = "v_table"
--})


for k, v in pairs(_G.python) do
    print(k, v)
end

print()


for v in python.iter(_G.python.builtins) do
    print(v)
end

local tab = {
    [1] = 2
}
