---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zWX1333091.
--- DateTime: 2024/7/3 13:34
---


if not raw_tostring then
    function raw_tostring(v)
        local res = tostring(v)
        res = string.gsub(res, "\n", "\\n")
        res = string.gsub(res, "\t", "\\t")
        res = string.gsub(res, "\r", "\\r")
        return res
    end
end

local function test_md5()
    require("md5")
    print(md5.sumhexa(123))
end

local function test_xml()
    require("xml")
    print(string.writeXML({
        ["a"] = "a",
        ["b"] = "b"
    }))
end

local function test_date()
    require("date")
    print("data:")
    for i, v in pairs(date) do
        print("  ", i, v)
    end
end

local function test_json()
    require("json")
    local data = json.encode({
        ["a"] = "a",
        ["b"] = "b",
        ["c"] = { 1, 2, 3 }
    })
    print(data)
    local tab = json.decode([[
    {
        "a":null,
        "b":123
    }
    ]])
    for i, v in pairs(tab) do
        print("  ", i, v)
    end
end

local function test_common()
    for i, v in pairs(_G) do
        if true or type(v) == "table" then
            print(i, v)
            if i == "package" then
                for i2, v2 in pairs(v) do
                    print("    ", string.format("%s\t%q", i2, raw_tostring(v2)))
                end
            elseif i == "md5" then
                for i2, v2 in pairs(v) do
                    print("    ", i2, v2)
                end
            end
        end
    end
end

local function test_lua_stdlib()
    require("std.string")
end

local function main()
    --test_common()

    test_md5()
    --test_xml() -- 有问题
    --test_date()
    --test_json()
    --test_lua_stdlib()
end

main()
